/*
 *     Generated by the NeXT Interface Builder.
 * 
 * History:
 *	27 Feb 91	Modified TBL to initialise NXArgv early on
 *	19 Mar 91	Page info deafults
 */

#import <stdlib.h>
#import <AppKit/NSApplication.h>
// #import <appkit/defaults.h>			/* TBL */
#import "HTUtils.h"				/* TBL */
#import <string.h>				/* TBL */
#import <libc.h>				/* TBL */
#import <AppKit/NSPrintInfo.h>			/* TBL */
#import <Foundation/NSUserDefaults.h>			/* TBL */

extern char * appDirectory;	/* Name of the directory containing the application */

/*	Get Integer default value
*/
static int int_default(const char * param)
{
    int	result = 0;
#warning DefaultsConversion: This used to be a call to NXGetDefaultValue with the owner "WorldWideWeb".  If the owner was different from your applications name, you may need to modify this code.
    const char * string = [[[NSUserDefaults standardUserDefaults] objectForKey:[NSString stringWithCString:param]] cString];
    if (string) sscanf(string, "%i", &result);
    return result;
}

void main(int argc, char *argv[])
{
//    NXArgc = argc;		/* TBL */
//    NXArgv = argv;		/* TBL */

    char *p;
    
#error DefaultsConversion: the NXDefaultsVector type is obsolete. Construct a dictionary of default registrations and use the NSUserDefaults 'registerDefaults:' method
    static NXDefaultsVector myDefaults = {
        { "PaperType", "Letter"},		// Non-USA users will have to override
	{ "LeftMargin", "72"},			//  (72) Space for ring binding
	{ "RightMargin", "36"},			//  (72) Note printers need some margin 
	{ "TopMargin", "36"},			// (108) All margins in points
	{ "BottomMargin", "36"},		// (108) PrintInfo defaults in brackets
	{ NULL, NULL}				// Terminate list.
    };
    
    
    appDirectory = malloc(strlen(argv[0]));
    strcpy(appDirectory, argv[0]);
    if (p = strrchr(appDirectory, '/')) p[1]=0;	/* Chop home directory after slash */
    if (TRACE) printf("WWW: Run from %s\n", appDirectory);

    NSApp = [NSApplication sharedApplication];
#error DefaultsConversion: NXRegisterDefaults() is obsolete. Construct a dictionary of default registrations and use the NSUserDefaults 'registerDefaults:' method
    NXRegisterDefaults("WorldWideWeb", myDefaults);
    [NSBundle loadNibNamed:@"WorldWideWeb.nib" owner:NSApp];

//	The deafult Margins seem to be 72, 72, 108, 108 which is a lot.    
    {
	int leftM = int_default("LeftMargin");
	int rightM = int_default("RightMargin");
	int topM = int_default("TopMargin");
	int bottomM = int_default("BottomMargin");
	
#warning PrintingConversion:  The current PrintInfo object now depends on context. '[NSPrintInfo sharedPrintInfo]' used to be '[NSApp printInfo]'. This might want to be [[NSPrintOperation currentOperation] printInfo] or possibly [[PageLayout new] printInfo].
        NSPrintInfo * pi = [NSPrintInfo sharedPrintInfo];
#warning DefaultsConversion: This used to be a call to NXGetDefaultValue with the owner "WorldWideWeb".  If the owner was different from your applications name, you may need to modify this code.
        [pi setPaperName:[[NSUserDefaults standardUserDefaults] objectForKey:@"PaperType"]];
	[pi setVerticallyCentered:NO];
#warning PrintingConversion: May be able to remove some of the [pi setXXXXMargin:] calls
	[pi setLeftMargin:leftM];

	[pi setRightMargin:rightM];

	[pi setTopMargin:topM];

	[pi setBottomMargin:bottomM]; // Points.
    }
    
    [NSApp run];
    [NSApp release];
    exit(0);
}
